# Generated by Django 4.2.30 on 2026-09-21 09:13

from django.db import migrations, models

import services.web.strategy_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_v2', '0027_migrate_rules_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrule',
            name='conditions',
            field=models.JSONField(
                blank=True,
                default=services.web.strategy_v2.models._default_dispatch_rule_conditions,
                help_text='匹配条件树（WhereCondition 结构），空 dict = 默认兜底规则',
                null=True,
                verbose_name='Conditions',
            ),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('disabled', 'Disabled'),
                    ('failed', 'Failed'),
                    ('start_failed', 'Start Failed'),
                    ('update_failed', 'Update Failed'),
                    ('stop_failed', 'Stop Failed'),
                    ('delete_failed', 'Delete Failed'),
                    ('starting', 'Starting'),
                    ('updating', 'Updating'),
                    ('stopping', 'Stopping'),
                    ('running', 'Running'),
                ],
                default='starting',
                max_length=64,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='strategyrule',
            name='conditions',
            field=models.JSONField(
                blank=True,
                default=services.web.strategy_v2.models._default_strategy_rule_conditions,
                help_text='检测条件，结构：{"where": {...}, "having": {...}}',
                verbose_name='Conditions',
            ),
        ),
    ]
