# Generated by Django 4.2.30 on 2026-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0064_risk_notice_group_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpermission',
            name='user_type',
            field=models.CharField(
                choices=[('operator', 'Operator'), ('notice_user', 'Notice User'), ('confirmer', 'Confirmer')],
                db_index=True,
                max_length=32,
                verbose_name='User Type',
            ),
        ),
    ]
